/* L�gico_4: */

CREATE TABLE CONVIDADO (
    CodConv INTEGER PRIMARY KEY,
    Nome VARCHAR(50),
    Email VARCHAR(50),
    Senha VARCHAR(10)
);

CREATE TABLE PROJETOS (
    CodProJ INTEGER PRIMARY KEY,
    Nome VARCHAR(50),
    Area VARCHAR(50),
    Data DATE,
    Criador VARCHAR(50),
    Descricao BLOB
);

CREATE TABLE ACESSA(
FOREIGNKEY CodPar REFERENCES PARTICIPANTES(CodPar);
FOREIGNKEY CodProJ REFERENCES PROJETOS(CodProJ);

)

CREATE TABLE PARTICIPANTES (
    CodPar INTEGER PRIMARY KEY,
    Nome VARCHAR(50),
    Senha VARCHAR(10),
    DataNascimento_ DATE,
    FORMACAO_ACADEMICA VARCHAR(50);
    E_mail VARCHAR(50)
);

CREATE TABLE VISUALIZA(
    FOREIGNKEY CodConv REFERENCES CONVIDADO(CodConv);  
    FOREIGNKEY CodAtiv REFERENCES ATIVIDADES(CodAtiv);

)

CREATE TABLE ATIVIDADES (
    CodAtiv PRIMARY KEY,
    Reflorestamento BLOB,
    Energia_renovavel BLOB
)

CREATE TABLE COLABORA(
    FOREIGNKEY CodPar REFERENCES PARTICIPANTES(CodPar);
    FOREIGNKEY CodCom REFERENCES COMUNIDADE(CodCom);

);



CREATE TABLE COMUNIDADE (
    CodCom INTEGER PRIMARY KEY,
    Data DATE,
    Criador VARCHAR(50),
    Remetente_ VARCHAR(50),    
    Area_ VARCHAR(50)
)FOREIGNKEY CodPar REFERENCES PARTICIPANTES(CodPar);